import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import HeaderSection from "@/components/HeaderSection";
import LayoutCompo from "@/components/store/LayoutCompo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
      <ToastContainer
position="top-center"
autoClose={2500}
hideProgressBar
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition={Slide}
/><LayoutCompo>
        <HeaderSection />
        {children}
        <Footer />
        </LayoutCompo>
        </body>
    </html>
  );
}
